spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://172.20.10.14/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.0.106/sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
  jackson:
    default-property-inclusion: non_null
server:
  port: 7070
  context-path: "/sell"